# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\code\python\Outsourcing\captcha\list.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QTableWidgetItem

from utils import Utils


class Ui_List(object):

    util=Utils()
    # def __init__(self,username):
    #     self.load(username)
    def setupUi(self, List):
        List.setObjectName("List")
        List.resize(552, 485)
        self.tableWidget = QtWidgets.QTableWidget(List)
        self.tableWidget.setGeometry(QtCore.QRect(70, 30, 341, 361))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.pushButton = QtWidgets.QPushButton(List)
        self.pushButton.setGeometry(QtCore.QRect(170, 420, 91, 31))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(List)
        QtCore.QMetaObject.connectSlotsByName(List)

    def retranslateUi(self, List):
        _translate = QtCore.QCoreApplication.translate
        List.setWindowTitle(_translate("List", "Form"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("List", "预测结果"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("List", "用户名"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("List", "模型"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("List", "验证码类型"))
        self.pushButton.setText(_translate("List", "返回"))

    def load(self,username):
        res = self.util.find_all(username)
        print(res, 'findaaa')
        for row, row_data in enumerate(res):
            self.tableWidget.setRowCount(row + 1)
            for col, data in enumerate(row_data):
                if col == 0 :
                    continue  # 跳过第一个字段
                self.tableWidget.setItem(row, col - 1, QTableWidgetItem(str(data)))  # 调整列索引
        print("查询成功")
